org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8

kotlin.daemon.jvm.options=-Xmx512M

android.useAndroidX=true

android.newDsl=false
android.builtInKotlin=false

org.gradle.caching=true
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.configureondemand=false

kotlin.incremental=false
kotlin.daemon.enabled=false